name: Acquire License

on: [push]

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Request Manual Activation File
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.10f1 # Match your Project version!

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.10f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
